# Generated by Django 4.2.7 on 2025-04-22 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personality', 'Personality'), ('aptitude', 'Aptitude')], max_length=20)),
                ('sub_category', models.CharField(choices=[('openness', 'Openness'), ('conscientiousness', 'Conscientiousness'), ('extraversion', 'Extraversion'), ('agreeableness', 'Agreeableness'), ('neuroticism', 'Neuroticism'), ('logical', 'Logical'), ('numerical', 'Numerical'), ('verbal', 'Verbal'), ('spatial', 'Spatial'), ('mechanical', 'Mechanical')], max_length=20)),
                ('question_text', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('correct_option', models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')])),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conscientiousness_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extraversion_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agreeableness_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('neuroticism_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AptitudeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numerical_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verbal_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spatial_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mechanical_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
