# Generated by Django 5.0.2 on 2025-04-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_add_assessment_questions'),
        ('assessment', '0002_remove_assessmentquestion_correct_option_and_more'),
    ]

    operations = [
    ]
