# Generated by Django 5.0.2 on 2025-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_merge_20250422_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerrecommendation',
            name='recommended_courses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='career_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='confidence_score',
            field=models.FloatField(),
        ),
    ]
