# Generated by Django 5.0.2 on 2025-04-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='areas_of_interest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='college_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='college_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('btech', 'B.Tech'), ('be', 'B.E'), ('bsc', 'B.Sc'), ('bcom', 'B.Com'), ('ba', 'B.A'), ('bba', 'BBA'), ('mbbs', 'MBBS'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='entrance_exams',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('it', 'Information Technology'), ('mech', 'Mechanical Engineering'), ('civil', 'Civil Engineering'), ('electrical', 'Electrical Engineering'), ('electronics', 'Electronics Engineering'), ('chemical', 'Chemical Engineering'), ('biotech', 'Biotechnology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('mathematics', 'Mathematics'), ('economics', 'Economics'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('hr', 'Human Resources'), ('psychology', 'Psychology'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='board',
            field=models.CharField(blank=True, choices=[('cbse', 'CBSE'), ('icse', 'ICSE'), ('state', 'State Board'), ('nios', 'NIOS')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stream',
            field=models.CharField(blank=True, choices=[('pcm', 'Science (PCM)'), ('pcb', 'Science (PCB)'), ('commerce', 'Commerce'), ('humanities', 'Humanities')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_type',
            field=models.CharField(blank=True, choices=[('12th', '12th Student'), ('college', 'College Student')], max_length=10, null=True),
        ),
    ]
