# Generated by Django 5.0.2 on 2025-04-23 16:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_career_percentage_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='areas_of_interest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='board',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college_cgpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entrance_exams',
        ),
        migrations.RemoveField(
            model_name='user',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenth_marks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twelfth_marks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_type',
            field=models.CharField(choices=[('12th', '12th Student'), ('college', 'College Student')], default='12th', max_length=10),
        ),
        migrations.CreateModel(
            name='CollegeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('course', models.CharField(choices=[('btech', 'B.Tech'), ('be', 'B.E'), ('bsc', 'B.Sc'), ('bcom', 'B.Com'), ('ba', 'B.A'), ('bba', 'BBA'), ('mbbs', 'MBBS'), ('other', 'Other')], max_length=20)),
                ('specialization', models.CharField(choices=[('cs', 'Computer Science'), ('it', 'Information Technology'), ('mech', 'Mechanical Engineering'), ('civil', 'Civil Engineering'), ('electrical', 'Electrical Engineering'), ('electronics', 'Electronics Engineering'), ('chemical', 'Chemical Engineering'), ('biotech', 'Biotechnology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('mathematics', 'Mathematics'), ('economics', 'Economics'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('hr', 'Human Resources'), ('psychology', 'Psychology'), ('other', 'Other')], max_length=20)),
                ('college_cgpa', models.DecimalField(decimal_places=2, help_text='Enter CGPA between 0 and 10', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('graduation_year', models.IntegerField(help_text='Expected year of graduation', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)])),
                ('areas_of_interest', models.JSONField(default=list, help_text='List of professional/career areas of interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'College Student Profile',
                'verbose_name_plural': 'College Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='SchoolStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('board', models.CharField(choices=[('cbse', 'CBSE'), ('icse', 'ICSE'), ('state', 'State Board'), ('nios', 'NIOS')], max_length=10)),
                ('stream', models.CharField(choices=[('pcm', 'Science (PCM)'), ('pcb', 'Science (PCB)'), ('commerce', 'Commerce'), ('humanities', 'Humanities')], max_length=20)),
                ('tenth_marks', models.DecimalField(decimal_places=2, help_text='Enter percentage between 0 and 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('twelfth_marks', models.DecimalField(decimal_places=2, help_text='Enter percentage between 0 and 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('entrance_exams', models.JSONField(default=list, help_text='List of entrance exams the student is preparing for')),
                ('areas_of_interest', models.JSONField(default=list, help_text='List of academic/career areas of interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Student Profile',
                'verbose_name_plural': 'School Student Profiles',
            },
        ),
    ]
