# Generated by Django 5.0.2 on 2025-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('engineering', 'Engineering'), ('medical', 'Medical'), ('dental', 'Dental'), ('pharmacy', 'Pharmacy'), ('law', 'Law'), ('management', 'Management'), ('architecture', 'Architecture & Planning'), ('general', 'General University')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('established', models.IntegerField(blank=True, null=True)),
                ('ownership', models.CharField(blank=True, max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('affiliated_to', models.CharField(blank=True, max_length=255)),
                ('facilities', models.TextField(blank=True)),
                ('courses_offered', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['ranking', 'name'],
            },
        ),
    ]
