# Generated by Django 5.0.2 on 2025-04-24 14:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_alter_college_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
