# Generated by Django 5.0.2 on 2025-04-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_alter_college_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='category',
            field=models.CharField(choices=[('eng', 'Engineering'), ('medical', 'Medical'), ('dental', 'Dental'), ('pharmacy', 'Pharmacy'), ('law', 'Law'), ('management', 'Management'), ('architecture', 'Architecture & Planning')], max_length=50),
        ),
    ]
