# Generated by Django 5.0.2 on 2025-04-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='ats_score',
            field=models.JSONField(default=dict),
        ),
    ]
